name: Expedia Pipeline
run-name: Build React Front-End Image
on: [push]
jobs:
  Test:
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: pwd
      - run: echo "Hello World."

#  Deploy:
#    runs-on: [self-hosted, Linux, x64]
#    steps:
#      - name: Checkout Code 
#        uses: actions/checkout@v2
#      - run: docker  
#      - run: echo "Hello World."
